version: "3.9"

services:
  postgres:
    image: postgres
    container_name: fileshare-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./pg-volume:/var/lib/postgresql/data
